### ISSUE TITLE
why not use namespace rapidmix:: ?

### ISSUE THREAD

**Issue by npisanti** [mzed/ofxRapidLib#7]
Hi!

as oF is[ moving toward a better use of namespaces](https://github.com/openframeworks/openFrameworks/issues/2581) why not use `rapidmix::` namespace as default like in the rapidmix API examples? if someone wants it could always use `using namespace rapidmix`, but global namespace are considered a bad pratice (that i'm trying to avoid).

PS: Thank you very much for the addon!

**Comment by mzed** [comment]
I'm not using rapidmix:: because this is only one of the libraries in rapidmix.

However, I'm not against using a namespace. Are there other examples of ofxAddons using namespaces? Is there a convention?

**Comment by npisanti** [comment]
there is no defined convetion, the recent oF version 0.10 don't use the `namespace std` anymore, and uses also the vector math by addressing the classes directl with `glm::`, some addons have started to use namespaces, for example ofxCv uses the `ofxCv` namespace, i also started to transition to use namespaces in all my addons, for now just ofxPDSP that is the biggest use the `pdsp` namespace. Mostly outside of oF in standard c++ it is a good practice to use namespaces.

**Comment by mzed** [comment]
I've added rapidlib:: as the namespace.  I'm still working through the examples for 0.10.0, but the basic code should be good.

**Comment by npisanti** [comment]
looking forward to test it again in the future!

**Comment by mzed** [comment]
FYI: this is currently happening in the of_0.10.0 branch. I'll merge into master once all the examples are working well.
